### ISSUE TITLE
Capture ESC character via FOR & PROMPT

### ISSUE THREAD

**Issue by amakvana** [cyl-vin/Scripty#1]
Capture the escape character using `FOR` and passing in `PROMPT`, rather than copying and pasting the character.

Example:

```
for /f %%a in ('echo prompt $E^| cmd') do set "ESC=%%a"
echo %ESC%[1ATest...
```

**Comment by cyl-vin** [comment]
I don't think I ever copy and pasted the character, I always did Alt+027 to get it, but I could see myself forgetting it in the future, so once again thank you!

**Comment by amakvana** [comment]
> I don't think I ever copy and pasted the character, I always did Alt+027 to get it, but I could see myself forgetting it in the future, so once again thank you!

Not all IDE's will insert the `ESC` character when `Alt+027` is used. This is why capturing it using the `FOR` loop technique is safer and guaranteed to work as long as VT100 sequences are enabled 

You also need the line below:
```
for /f %%a in ('echo prompt $E^| cmd') do set "ESC=%%a"
```

Place right under `setlocal enableDelayedExpansion` on line 2

**Comment by cyl-vin** [comment]
It should be fine as it is now right? I just ended up using the ESC character for all the colors I need instead of %colorcodehere%. Would it affect people that just use the script or should I just replace them all just to be safe using your suggestion?

**Comment by amakvana** [comment]
> It should be fine as it is now right? I just ended up using the ESC character for all the colors I need instead of %colorcodehere%.

This is fine. However, I would still capture the ESCAPE key using the technique I've shown and reference it using `%ESC%`.

One of the other reasons is readability:

`` could be any `Alt+XXXX` keycode combination, whereas referencing it with `%ESC%` tells user that this is the ESCAPE key.

See example below on how to implement it:

```
@echo off
setlocal enabledelayedexpansion
for /f %%a in ('echo prompt $E^| cmd') do set "ESC=%%a"
mode con: cols=65 lines=26
:main
title Scripty coded by cylvin
cls
echo %ESC%[36m----------------------------------------------------------------%ESC%[0m
echo %ESC%[34m   _____           _       __         %ESC%[0m      %ESC%[33mMade By:%ESC%[0m %ESC%[34mcylvin%ESC%[0m
echo %ESC%[34m  / ___/__________(_)___  / /___  __  %ESC%[0m%ESC%[92mgithub.com/cyl-vin/Scripty%ESC%[0m
echo %ESC%[34m  \__ \/ ___/ ___/ / __ \/ __/ / / /  %ESC%[0m
echo %ESC%[34m ___/ / /__/ /  / / /_/ / /_/ /_/ /   %ESC%[0m
echo %ESC%[34m/____/\___/_/  /_/ .___/\__/\__, /    %ESC%[0m
echo %ESC%[34m                /_/        /____/%ESC%[0m v1.0
echo %ESC%[36m----------------------------------------------------------------%ESC%[0m
```

**Comment by cyl-vin** [comment]
The escape character for me is visible as [ESC], probably because I edit in notepad++ but I'm changing it anyways as per your suggestion since I do actually want other people to be able to modify the code if they need to :D Thank you as always
