### ISSUE TITLE
Use REM for comments, instead of ::

### ISSUE THREAD

**Issue by amakvana** [cyl-vin/Scripty#3]
When `::` labels are used as comments within a [bracketed code block](https://ss64.com/nt/syntax-brackets.html) or FOR command, the command processor will expect (not unreasonably) that every label is followed by at least one command. (That way if you jump to the label it will have something to execute.) In fact the CMD shell will attempt to execute the second line [even if it is formatted as a label](https://ss64.org/viewtopic.php?f=2&t=118).
Anything which is not a valid command, even a blank line or a closing parenthesis will cause a :: style comment to fail:

```
(
 Echo This example will fail
 :: some comment
)
```
```
(
 :NormalLabel & Echo this will not be executed.
 :SecondaryLine & Echo This will be executed.
) 
```
When working within parentheses/brackets it is safer to use REM for all comment lines.

```
(
 REM something & Echo this will not be executed.
 REM somethingelse & Echo This also will not be executed.
)
```

**Comment by cyl-vin** [comment]
I didn't even know that could be an issue, tyty
