### ISSUE TITLE
Refactor of :colors block 

### ISSUE THREAD

**Issue by amakvana** [cyl-vin/Scripty#5]
You can refactor your `:colors` block of code, simplified to this:

```
:colors
cls
for /f "tokens=2 delims==" %%a in ('set b') do (
    for /f "tokens=2 delims==" %%b in ('set cd') do (
        echo %%~b%%~aTesting all of the possible color combinations%cr%
    )
    for /f "tokens=2 delims==" %%b in ('set cb') do (
        echo %%~b%%~aTesting all of the possible color combinations%cr%
    )
    echo %fbb%%%~aTesting all of the possible color combinations%cr%
    echo %cw%%%~aTesting all of the possible color combinations%cr%
)
pause
goto main
```

How this works:

1. The outer loop (`for /f "tokens=2 delims==" %%a in ('set b')`) iterates through environment variables that start with the letter “b”. For each variable, it extracts the second token (value) using `tokens=2` and the delimiter “=” using `delims=="`. The extracted value is stored in the variable `%%a`.
2. Inside the outer loop, there are two nested inner loops:
a. The first inner loop (`for /f "tokens=2 delims==" %%b in ('set cd')`) iterates through environment variables that start with the letters “cd”. Similar to the outer loop, it extracts the second token (value) and stores it in the variable `%%b`.
b. The second inner loop (`for /f "tokens=2 delims==" %%b in ('set cb')`) iterates through environment variables that start with the letters “cb”. Again, it extracts the second token (value) and stores it in the variable `%%b`.
3. Within each inner loop, the script echoes a message combining the values from the variables `%%a` and `%%b`. The `%%~b` syntax removes any surrounding quotes from the value.
4. After the inner loops, the script echoes two additional messages, for the remaining variables which did not conform to the conditions of the inner loops above:
a. `%fbb%%%~aTesting all of the possible color combinations%cr%`
b. `%cw%%%~aTesting all of the possible color combinations%cr%`

Test accordingly

**Comment by cyl-vin** [comment]
Just ended up removing the color display in the end as I didn't really need it anymore. It was just used as a color palette for when I was experimenting with the colors. This would be great to have for future reference though so thank you!
